import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Trabalho final da disciplina de <a href='#'>Ruby on Rails!</a>
        </h1>

        <div className={styles.grid}>
          <a href="http://localhost:4000/books" className={styles.card}>
            <h2>Livros &rarr;</h2>
            <p>Listar os livros cadastrados.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Autores &rarr;</h2>
            <p>Listar os autores cadastrados.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Editoras &rarr;</h2>
            <p>Listar as editoras cadastradas.</p>
          </a>

          <a
            href="#"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Categorias &rarr;</h2>
            <p>Listar as categorias cadastradas.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/brunoreolon"
          target="_blank"
          rel="gihub brunoreolon"
        >
          Powered by Bruno Reolon
        </a>
      </footer>
    </div>
  )
}
